server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
      - id: core-service
        uri: lb://DIVACORE-SERVICE
        predicates:
          - Path=/core/**
        filters:
           - AuthenticationFilter 
      - id: auth-service
        uri: lb://SECURITY-SERVICE
        predicates:
          - Path=/auth/**
        filters:
           - AuthenticationFilter  
  
  application:
    name: API-GATEWAY         

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
